### ISSUE TITLE
Get Vector chart ready for 0.1.0 release

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/helm-charts#38]
Issue to track identified gaps, bugs, etc prior to releasing the new `vector` chart at 0.1.0

- [x] haproxy always includes default Aggregator ports in its service #40 
- [x] #70
- [x] api section in custom config doesn't generate port definitions
- [ ] https://github.com/vectordotdev/vector/issues/7901
- [x] https://github.com/vectordotdev/vector/issues/7902
- [x] #87
- [x] #88
- [x] #90
